apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trillian-logserver-1-5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trillian-logserver-1-5
    app.kubernetes.io/part-of: trillian
  name: trillian-logserver-1-5
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/instance: trillian-logserver-1-5
status:
  loadBalancer: {}
